version: "3.3" #dockercomposer version

networks:
    bibbox-default-network:
        external: true

services:

    bibbox-labelstudio-nginx:
        image: heartexlabs/label-studio:1.6.0
        container_name:  bibbox-labelstudio-nginx
        restart: unless-stopped
        networks:
          - bibbox-default-network
        links:
          -  bibbox-labelstudioapp:app
        ports:
          - "8080:80"
          - "8081:443"
        depends_on:
          - bibbox-labelstudioapp
        environment:
          - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
        volumes: 
          - ./data/mydata:/label-studio/data:rw
          - ./data/deploy/nginx/certs:/certs:ro
        command: nginx
        
    bibbox-labelstudioapp:
        stdin_open: true
        tty: true
           # build: .
        image: heartexlabs/label-studio:1.6.0
        container_name:  bibbox-labelstudioapp
        restart: unless-stopped
        networks:
          - bibbox-default-network
        #links:
        #  - bibbox-app-db:db
        expose:
          - "8080"
        depends_on:
          - db
        environment:
          - DJANGO_DB=default
          - POSTGRE_NAME=postgres
          - POSTGRE_USER=postgres
          - POSTGRE_PASSWORD=
          - POSTGRE_PORT=5432
          - POSTGRE_HOST=db
          - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
          - JSON_LOG=1
        volumes: 
          - ./data/data/container/app-data:/app-data
        command: label-studio-uwsgi

        image: postgres:11.5
        hostname: db
        restart: always
        # Optional: Enable TLS on PostgreSQL
        # Just drop your server.crt and server.key into folder 'deploy/pgsql/certs'
        # NOTE: Both files must have permissions u=rw (0600) or less
        #command: >
         # -c ssl=on
          #-c ssl_cert_file=/var/lib/postgresql/certs/server.crt
          #-c ssl_key_file=/var/lib/postgresql/certs/server.key
        environment:
          - POSTGRES_HOST_AUTH_METHOD=trust
          - PGDATA=/var/lib/postgresql/data/mydata
        volumes:
          - ./data/postgres-data:/var/lib/postgresql/mydata:z
          - ./data/deploy/pgsql/certs:/var/lib/postgresql/certs:ro
        networks:
          - bibbox-default-network


volumes:
    static: {}


